[package]
name = "pyscription"
version = "0.1.0"
edition = "2024"
description = "Simple Python docstring parser"

[dependencies]
anyhow = "1.0.100"
thiserror = "2.0.17"
clap = { version = "4.5.51", features = ["derive"] }
